version: "3.3"

services:
  nginx:
    depends_on:
      - springboot
    image: localhost:5000/deviad-nginx
    restart: always
    ports:
        - "8081:80"
    restart: always
    networks:
      - simplicity_backend
  springboot:
    depends_on:
      - db-service
    image: localhost:5000/simplicity-springdemo
    restart: always
    environment:
      - SERVER_PORT=5050
      - DB_NAME=springdemo
      - DB_USERNAME=springuser
      - DB_PASSWORD=springpassword
      - ACTIVE_PROFILE=development 
      - CLIENT_ID=fooClientIdPassword
      - DB_HOSTNAME=db-service
      - CLIENT_SECRET=secret
      - APP_HOSTNAME=localhost
      - DDL_AUTO=create-drop
      - JWT_SIGNING_KEY=supersecretkey
      - DB_DBMS=mariadb
    ports:
      - "5050:5050"
    networks:
      - simplicity_backend 
  db-service: 
    image: wodby/mariadb  
    volumes: 
      - db-data:/var/lib/mysql
    environment: 
      - MYSQL_USER=springuser
      - MYSQL_PASSWORD=springpassword
      - MYSQL_DATABASE=springdemo
      - MYSQL_ROOT_PASSWORD=springdemo
    ports:
      - "3336:3306"
    networks:
      - simplicity_backend    

volumes:
  db-data:

networks:
  simplicity_backend: